### ISSUE TITLE
Add Favorites menu with new UI

### ISSUE THREAD

**Issue by Patrick-van-Halm** [Patrick-van-Halm/dv-multiplayer-mod#11]
Maybe add an option to save strings/servers, in case of someone having a static IP or DynDNS, that would be useful!
`Requested by LillyElijahWho on discord`

**Comment by LillyWho** [comment]
Could be solved by saving to and reading fron a simple text file.
For fancier solutions and for not having to make up your own syntax, json or XML would be ideal.

Why formatting?
Because you could give different nicknames to different IPs/hostnames:

```
<hostname="1.1.1.1" name="Jeff" />
<hostname="dwaynetheblockjohnson.dynv6.net" name="Johnson" />

```
Easy to edit, easy to parse!
Especially with IPs, a nickname solution would make it easier to distinguish between list entries.

**Comment by Patrick-van-Halm** [comment]
I was also thinking of maybe adding port as a value in these.
